---
- name: Dell Switch Config Backup Demo
  hosts: z9100-01
  gather_facts: false
  #connection: network_cli
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic.sonic_config

  tasks:
    - name: Backup current switch config (dell sonic)
      dellemc.enterprise_sonic.sonic_config:
        backup: yes
          backup_options:
            dir_path: /opt/sonic_backups
            filename: backup-cfg-"{{inventory_hostname}}"

